### PR TITLE
Check for empty values in MessageEmbed as well as violations of the 6000-char limit

### LINKED ISSUE #102: Empty MessageEmbed field value leads to "Invalid Form Body" API response
**Please describe the issue you are having:**
When creating a new Embed, if you were to leave a field blank, the bot doesn't pick up on it, until it hits the embed, then it only warns the user and continues. Discord required all fields to be non-empty.

**If you are encountering any errors, post the full stack trace here:**
grafik

**Please include a Minimal, Complete and Verifiable Example:**
```php
$embed = new MessageEmbed();
$embed->setColor(6447835)
    ->setDescription("Description!")
    ->addField("", "This is a blank field!")
    ->addField("So is this one!", "")
    ->setTimestamp();

$channel->send("", ['embed' => $embed])->done(null, function ($error) {
    echo $error.PHP_EOL;
});
```
**Further details:**

- Yasmin version: v0.6.1
- PHP version: 7.1.27
- Operating System: Ubuntu 18.04.2

- [ ✔️ ] I have also tested the issue on latest master with commit hash: 08982ba

### PR DESCRIPTION
**Pull request by sylae**
**Pull Request description:**
* Resolves #102
* Checks that the 6000-character overall limit is not passed
* Performs validations when passing values via the constructor
* Yeets some whitespace on blank lines because I guess my IDE doesn't like that

**Why should this Pull Request be merged:**
Resolves #102 as well as some other uncaught errors in embed validation.

**Semantic Versioning Classification:**
- [ ] This PR includes major breaking changes (such as method changes)
- [ ] This PR includes **only** documentational changes (such as docblocks, README, etc.)

### CODE REVIEW

File: src/Models/MessageEmbed.php [hunk 1]
```diff
@@ -354,4 +412,25 @@ function addField($title, $value, bool $inline = false) {
         
         return $this;
     }
+    
+    /**
+     * Checks to see if adding a property has put us over Discord's 6000-char overall limit.
+     * @return bool
+     */
+    protected function exceedsOverallLimit(int $addition = 0): bool {
+        $total = array_sum(array(
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]: Please collapse this into a cheap addition operation.

File: src/Models/MessageEmbed.php [hunk 2]
```diff
@@ -346,6 +400,10 @@ function addField($title, $value, bool $inline = false) {
             throw new \InvalidArgumentException('Embed value can not be longer than 1024 characters');
         }
         
+        if ($this->exceedsOverallLimit((\mb_strlen($value) + \mb_strlen($title)))) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]: CS: whitespace
nit: Variable order

File: src/Models/MessageEmbed.php [hunk 3]
```diff
@@ -167,10 +173,16 @@ function __construct(array $embed = array()) {
                 );
             }
             
-            $this->fields = $embed['fields'] ?? array();
+            foreach ($embed['fields'] ?? array() as $field) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]: CS: whitespace, missing parens

File: src/Models/MessageEmbed.php [hunk 4]
```diff
@@ -34,143 +34,158 @@ class MessageEmbed extends Base {
...
      * Constructs a new instance.
      * @param array  $embed
      */
     function __construct(array $embed = array()) {
         if(!empty($embed)) {
             $this->type = $embed['type'] ?? 'rich';
-            $this->title = $embed['title'] ?? null;
-            
+
+            if (!empty($embed['title'])) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
            if(!empty($embed['title'])) {
```

File: src/Models/MessageEmbed.php [hunk 5]
```diff
@@ -114,25 +114,31 @@ class MessageEmbed extends Base {
...
-                    'url' => ((string) ($embed['author']['url'] ?? ''))
+                $this->setAuthor(
+                    ((string) ($embed['author']['name'] ?? '')),
+                    ((string) ($embed['author']['icon_url'] ?? '')),
+                    ((string) ($embed['author']['url'] ?? ''))
                 );
             }
             
-            $this->description = $embed['description'] ?? null;
+            if (!empty($embed['description'])) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
            if(!empty($embed['description'])) {
```

File: src/Models/MessageEmbed.php [hunk 6]
```diff
@@ -202,10 +214,19 @@ function __get($name) {
...
+        if(\mb_strlen($name) === 0) {
+            $this->author = null;
+            return $this;
+        }
+        
         if(\mb_strlen($name) > 256) {
             throw new \InvalidArgumentException('Author name can not be longer than 256 characters.');
         }
         
+        if ($this->exceedsOverallLimit(\mb_strlen($name))) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
        if($this->exceedsOverallLimit(\mb_strlen($name))) {
```

File: src/Models/MessageEmbed.php [hunk 7]
```diff
@@ -235,15 +260,25 @@ function setColor($color) {
...
+            $this->description = null;
+            return $this;
+        }
+
         if(\mb_strlen($description) > 2048) {
             throw new \InvalidArgumentException('Embed description can not be longer than 2048 characters');
         }
-        
+
+        if ($this->exceedsOverallLimit(\mb_strlen($description))) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
        if($this->exceedsOverallLimit(\mb_strlen($description))) {
```

File: src/Models/MessageEmbed.php [hunk 8]
```diff
@@ -254,10 +284,20 @@ function setDescription($description) {
     function setFooter($text, string $iconurl = '') {
         $text = (string) $text;
         
+        if(\mb_strlen($text) === 0) {
+            // if footer text is an empty string, Discord gets mad. null it instead.
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
```

File: src/Models/MessageEmbed.php [hunk 9]
```diff
@@ -254,10 +284,20 @@ function setDescription($description) {
...
+            $this->footer = null;
+            return $this;
+        }
+        
         if(\mb_strlen($text) > 2048) {
             throw new \InvalidArgumentException('Footer text can not be longer than 2048 characters.');
         }
         
+        if ($this->exceedsOverallLimit(\mb_strlen($text))) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
        if($this->exceedsOverallLimit(\mb_strlen($text))) {
```

File: src/Models/MessageEmbed.php [hunk 10]
```diff
@@ -303,10 +343,20 @@ function setTimestamp(?int $timestamp = null) {
      * @throws \InvalidArgumentException
      */
     function setTitle(string $title) {
+        if(\mb_strlen($title) == 0) {
+            // if title is an empty string, Discord gets mad. null it instead.
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
```

File: src/Models/MessageEmbed.php [hunk 11]
```diff
@@ -303,10 +343,20 @@ function setTimestamp(?int $timestamp = null) {
...
+            $this->title = null;
+            return $this;
+        }
+        
         if(\mb_strlen($title) > 256) {
             throw new \InvalidArgumentException('Embed title can not be longer than 256 characters');
         }
         
+        if ($this->exceedsOverallLimit(\mb_strlen($title))) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
        if($this->exceedsOverallLimit(\mb_strlen($title))) {
```

File: src/Models/MessageEmbed.php [hunk 12]
```diff
@@ -354,4 +412,25 @@ function addField($title, $value, bool $inline = false) {
...
+     */
+    protected function exceedsOverallLimit(int $addition = 0): bool {
+        $total = (
+            \mb_strlen(($this->title ?? "")) +
+            \mb_strlen(($this->description ?? "")) +
+            \mb_strlen(($this->footer['text'] ?? "")) +
+            \mb_strlen(($this->author['name'] ?? ""))
+        );
+        
+        foreach ($this->fields as $field) {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
        foreach($this->fields as $field) {
```

File: src/Models/MessageEmbed.php [hunk 13]
```diff
@@ -354,4 +412,25 @@ function addField($title, $value, bool $inline = false) {
...
+    /**
+     * Checks to see if adding a property has put us over Discord's 6000-char overall limit.
+     * @return bool
+     */
+    protected function exceedsOverallLimit(int $addition = 0): bool {
+        $total = (
+            \mb_strlen(($this->title ?? "")) +
+            \mb_strlen(($this->description ?? "")) +
+            \mb_strlen(($this->footer['text'] ?? "")) +
+            \mb_strlen(($this->author['name'] ?? ""))
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
            \mb_strlen(($this->author['name'] ?? "")) +
            $addition
```

File: src/Models/MessageEmbed.php [hunk 14]
```diff
@@ -354,4 +412,25 @@ function addField($title, $value, bool $inline = false) {
...
+        );
+        
+        foreach ($this->fields as $field) {
+            $total += \mb_strlen($field['name']);
+            $total += \mb_strlen($field['value']);
+        }
+        
+        $total += $addition;
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
```

File: src/Models/MessageEmbed.php [hunk 15]
```diff
@@ -354,4 +412,25 @@ function addField($title, $value, bool $inline = false) {
         
         return $this;
     }
+    
+    /**
+     * Checks to see if adding a property has put us over Discord's 6000-char overall limit.
+     * @return bool
+     */
+    protected function exceedsOverallLimit(int $addition = 0): bool {
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
    protected function exceedsOverallLimit(int $addition): bool {
```

File: src/Models/MessageEmbed.php [hunk 16]
```diff
@@ -190,7 +202,7 @@ function __get($name) {
         
         return parent::__get($name);
     }
-    
+
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
    
```

File: src/Models/MessageEmbed.php [hunk 17]
```diff
@@ -167,10 +173,16 @@ function __construct(array $embed = array()) {
...
+                $this->addField(
+                    ((string) ($field['name'] ?? '')),
+                    ((string) ($embed['value'] ?? '')),
+                    ((bool) ($embed['inline'] ?? false))
+                );
+            }
         }
     }
-    
+
```
Comment (CharlotteDunois) [inline src/Models/MessageEmbed.php]:
```suggestion
    
```

**Comment by CharlotteDunois** [comment]
Thanks!
